default:
  image: debian:stable

stages:
  - build
  - test

compile:
    stage: build
    script:
        - autoreconf -i
        - ./configure
        - make

run_test:
    stage: test
    script:
      - make check