#image: debian
image: gcc

before_script:
  - apt update
  - apt -y install make cmake libopenblas-dev fflas-ffpack

stages:
  - build
  - test

compile:
  stage: build
  script:
    - make

unit_tests:
    stage: test
    dependencies: compile
    script:
      - make check

long_tests:
    stage: test
    dependencies: compile
    script:
      - make check
