#image: debian
image: gcc

before_script:
  - apt update
  - apt -y install make autoconf automake libtool


stages:
  - build_and_test
  - longer_tests

compile:
  stage: build_and_tests
  script:
    - autoreconf -i
    - mkdir build
    - cd build
    - ../configure
    - make
    - make check
  artifacts:
    paths:
      - "build"


run_test:
    stage: longer_tests
    script:
      - echo "we must rebuild everything"
      - echo "and launch bigger tests"
