image: debian:12

before_script:
  - apt update
  - apt -y install build-essential pkg-config gcc g++ clang make cmake libopenblas-dev fflas-ffpack

stages:
  - build
  - test

compile_gcc:
  stage: build
  script:
    - make

compile_clang:
  stage: build
  script:
    - CC=clang make

unit_tests:
    stage: test
    script:
      - make check

long_tests:
    stage: test
    script:
      - make longtests
