#image: debian
image: gcc

before_script:
  - apt update
  - apt -y install make cmake

stages:
  - build
  - test

compile:
  stage: build
  script:
    - make

run_test:
    stage: test
    script:
      - make check
